name: stylegan3
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - click=8.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.7
  - pillow=9.4.0
  - pip:
      - diffusers==0.20.2
      - invisible_watermark==0.2.0
      - transformers==4.33.1
      - accelerate==0.22.0
      - safetensors==0.3.3
